name: Build # workflow

on: # event
  push:

jobs:
  job1: # job
    runs-on: ubuntu-latest # runner
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          repository: 'actions/setup-node'

      - name: Step 1
        run: cat README.md
