name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          workflow_conclusion: success
          name: my-artifact

      - name: List Files
        run: ls -l